import test from 'node:test';import assert from 'node:assert/strict';import {cases,blank,gaps,same,validateFile} from '../lib/cases.ts';
test('incomplete assessments cannot pass documentation gate',()=>{assert.equal(gaps(cases[0],blank().draft).length,6)});
test('each scenario has unique evidence and separate review questions',()=>{for(const c of cases){assert.equal(new Set(c.documents.map(x=>x.id)).size,c.documents.length);assert(c.questions.length);assert(c.party.startsWith('DEMO'))}assert(cases[0].questions.some(x=>x[3]==='Export controls'))});
test('editing a draft cannot change a submitted clone',()=>{const d=blank().draft;const snap=structuredClone(d);assert(same(d,snap));d.notes='New evidence';assert(!same(d,snap));assert.equal(snap.notes,'')});
test('portable files preserve saved draft and QC rationale',()=>{const s=blank();s.draft.notes='E1 supports a request for details';s.draft.pins=['E1'];s.history.push({at:new Date().toISOString(),review:structuredClone(s.draft),outcome:'Returned for correction',finding:'Clarify E1',reviewer:'Reviewer'});const f={format:'sanctions-review-desk',version:1,cases:{'SR-101':s}};assert.deepEqual(validateFile(JSON.parse(JSON.stringify(f))),f.cases)});
test('dangling evidence, unknown dispositions and malformed QC are rejected',()=>{for(const mutate of [(s:any)=>s.draft.pins=['unknown'],(s:any)=>s.draft.disposition='Clear shipment',(s:any)=>s.history=[{at:'bad'}],(s:any)=>s.draft.comparisons.Name='Auto cleared']){const s=blank();mutate(s);assert.throws(()=>validateFile({format:'sanctions-review-desk',version:1,cases:{'SR-101':s}}))}});
test('wrong schema rejected and case notes remain literal text',()=>{assert.throws(()=>validateFile({version:2}));const s=blank();s.draft.notes='<script>not executable</script>';assert.equal(validateFile({format:'sanctions-review-desk',version:1,cases:{'SR-102':s}})['SR-102'].draft.notes,s.draft.notes)});

import {changes,submitReview,reviewReport} from '../lib/cases.ts';
const complete=()=>{const s=blank();Object.assign(s.draft,{analyst:'Analyst',notes:'E1 requires corroboration',rationale:'Request identifiers',disposition:'More information needed',pins:['E1'],comparisons:Object.fromEntries(cases[0].fields.map(([k])=>[k,'Unknown / unverified']))});return s};
test('QC return requires an analyst response before resubmission',()=>{let s=submitReview(cases[0],complete());assert.throws(()=>submitReview(cases[0],s),/pending/);s.history[0].outcome='Returned for correction';s.history[0].finding='Clarify identifiers';s.history[0].reviewer='QC';assert.throws(()=>submitReview(cases[0],s),/Respond/);s.history[0].response='Updated rationale';s.draft.rationale='Request the corporate registry';const n=submitReview(cases[0],s);assert.equal(n.history.length,2);assert.equal(n.history[0].review.rationale,'Request identifiers');assert.equal(n.history[1].review.rationale,'Request the corporate registry')});
test('change comparison ignores object key order and identifies revised fields',()=>{const a=complete().draft,b=structuredClone(a);b.comparisons=Object.fromEntries(Object.entries(b.comparisons).reverse());assert(same(a,b));b.notes='Revised';assert.deepEqual(changes(a,b).map(x=>x.label),['Evidence assessment'])});
test('handoff report contains actual pinned evidence and selected requests',()=>{const s=complete();s.draft.requests.identity=true;const text=reviewReport(cases[0],s);assert(text.includes(cases[0].documents[0].body));assert(text.includes('Obtain business identifiers'));assert(text.includes('Not live screening'));assert(text.includes('https://ofac.treasury.gov/faqs/5'))});
test('responses round trip and malformed histories are rejected',()=>{const s=complete();s.history=[{at:new Date().toISOString(),review:structuredClone(s.draft),reviewer:'QC',finding:'Correct',response:'Addressed',outcome:'Returned for correction'}];const wrap=()=>({format:'sanctions-review-desk',version:1,cases:{'SR-101':s}});assert.equal(validateFile(wrap())['SR-101'].history[0].response,'Addressed');(s.history[0] as any).response=42;assert.throws(()=>validateFile(wrap()),/response/);delete s.history[0].response;s.history[0].outcome='Pending QC';s.history.push(structuredClone(s.history[0]));assert.throws(()=>validateFile(wrap()),/latest/)});
