export const guidance = [
 {name:'OFAC · Assessing name matches',url:'https://ofac.treasury.gov/faqs/5'},
 {name:'OFAC · Ownership and the 50 Percent Rule',url:'https://ofac.treasury.gov/faqs/401'},
 {name:'BIS · Freight forwarder due diligence',url:'https://www.bis.gov/learn-support/export-compliance-programs/freight-forwarder-guidance'},
];
export const cases=[
 {id:'SR-101',title:'An unexpected onward destination',type:'Business',subtitle:'Electronics shipment · California → Hong Kong → Shenzhen',trigger:'A fictional name-match alert coincides with a request to change the final consignee.',party:'DEMO Harbor Circuit Trading Ltd',role:'Buyer / distributor',route:['California','Hong Kong','Shenzhen'],goods:'400 smartphones · fictional order',scope:'U.S. sanctions review, with export-control questions referred separately.',fields:[['Name','DEMO Harbor Circuit Trading Ltd','DEMO Harbor Circuit Industrial Ltd'],['Registration','HK-DEMO-1048','Not supplied in mock entry'],['Address','Demo Warehouse A, Hong Kong','Demo Building B, Hong Kong'],['Ownership','Two shareholders; full chain unavailable','Not supplied in mock entry']],documents:[{id:'E1',title:'Purchase order',body:'Synthetic PO-1048: buyer requests delivery to a Hong Kong distributor. Declared final use: resale. The ultimate customer is not identified.'},{id:'E2',title:'Destination amendment',body:'Synthetic message: after the order, the buyer requests onward delivery to a Shenzhen recipient. Recipient registration details and signed end-use statement are absent.'},{id:'E3',title:'Mock screening alert',body:'TRAINING RECORD ONLY. The name resembles a fictional candidate entry. No real sanctions designation is asserted. The registration identifier is unavailable for comparison.'},{id:'E4',title:'Corporate profile',body:'Synthetic profile identifies two direct shareholders, but does not provide their ownership percentages or the full ownership chain.'}],questions:[['identity','Obtain business identifiers','Registration details are needed to investigate the possible name match.','Sanctions'],['ownership','Establish ownership','Document owners, percentages and relevant list status; do not infer a result from the name alone.','Sanctions'],['recipient','Identify the ultimate recipient','Request recipient registration, intended use and reason for the change.','Diversion'],['classification','Refer classification and authorization','Confirm product-specific classification and applicable export authorization with the trade team.','Export controls']],alternative:'An ordinary distributor may have a legitimate customer in Shenzhen. The route change is a question to investigate, not proof of evasion.'},
 {id:'SR-102',title:'A similar name, different identifiers',type:'Individual',subtitle:'Individual alert · identity comparison',trigger:'A fictional purchaser shares a similar name with a fictional screening candidate.',party:'DEMO Alex Morgan',role:'Individual purchaser',route:[],goods:'Identity review · no shipment conclusion',scope:'Resolve a simulated individual name match using corroborating identifiers.',fields:[['Name','DEMO Alex Morgan','DEMO Alexander Morgan'],['Date of birth','1988-04-12 (synthetic)','1962-11-03 (synthetic)'],['Nationality','Canada (synthetic)','United Kingdom (synthetic)'],['Identifier','DEMO-ID-204 (unverified)','DEMO-ID-889 (mock)']],documents:[{id:'E1',title:'Synthetic customer record',body:'Training customer: DEMO Alex Morgan. The supplied birth date and nationality differ from the mock candidate. Identity documents have not been independently verified.'},{id:'E2',title:'Mock candidate record',body:'TRAINING RECORD ONLY: DEMO Alexander Morgan, synthetic date of birth 1962-11-03. This record is not an OFAC entry and does not imply any real person is sanctioned.'}],questions:[['identity','Corroborate the identifiers','Determine whether the supplied identity information is reliable before relying on differences.','Sanctions'],['source','Record the screening source','For real work, preserve the full official entry and screening date; this demo has neither live list coverage nor a real match.','Sanctions']],alternative:'Similar names can belong to different people. Record which reliable identifiers support or challenge the match.'},
 {id:'SR-103',title:'The payer is not the buyer',type:'Business',subtitle:'Electronics shipment · Vietnam → China',trigger:'A fictional third-party payment and incomplete end-user information prompt review.',party:'DEMO Mekong Device Supply',role:'Buyer / exporter',route:['Vietnam','China'],goods:'600 refurbished devices · fictional order',scope:'Party and payment context for sanctions triage; product and reexport analysis requires specialist review.',fields:[['Buyer','DEMO Mekong Device Supply','No candidate supplied'],['Payer','DEMO Blue Lantern Services','Not screened in this exercise'],['Recipient','Not documented','Not screened in this exercise'],['Ownership','Unknown','Unknown']],documents:[{id:'E1',title:'Synthetic invoice',body:'The Vietnam-based buyer orders refurbished devices for a customer in China. The invoice names a different payer and contains no explanation of the relationship.'},{id:'E2',title:'Payment note',body:'Synthetic payment reference names DEMO Blue Lantern Services. No supporting agreement or ownership information is provided. Product origin and classification are not documented.'}],questions:[['payer','Explain the third-party payer','Request the relationship to the buyer and the reason for the payment arrangement.','Sanctions'],['recipient','Identify and screen all parties','Obtain the ultimate recipient and relevant ownership records. No list screening has been performed here.','Sanctions'],['classification','Refer reexport questions','Product origin, classification and jurisdiction must be established before assessing applicable export rules.','Export controls']],alternative:'A disclosed financing or group-company arrangement could explain the payer. Different parties and a cross-border route do not establish wrongdoing.'},
];
export type TrainingCase=typeof cases[number];
export type Review={comparisons:Record<string,string>;requests:Record<string,boolean>;notes:string;pins:string[];disposition:string;rationale:string;analyst:string};
export type Submission={at:string;review:Review;reviewer:string;finding:string;outcome:string};
export type CaseState={draft:Review;history:Submission[]};
export const blank=():CaseState=>({draft:{comparisons:{},requests:{},notes:'',pins:[],disposition:'',rationale:'',analyst:''},history:[]});
export function gaps(c:TrainingCase,d:Review){return [...(!d.analyst.trim()?['Analyst reference']:[]),...(!d.notes.trim()?['Evidence assessment']:[]),...(!d.rationale.trim()?['Disposition rationale']:[]),...(!d.disposition?['Proposed disposition']:[]),...(!d.pins.length?['Supporting evidence']:[]),...(c.fields.some(([k])=>!d.comparisons[k])?['Compare each party field']:[])]}
export function same(a:Review,b:Review){return JSON.stringify(a)===JSON.stringify(b)}
export function validateFile(x:any):Record<string,CaseState>{if(x?.format!=='sanctions-review-desk'||x.version!==1||!x.cases)throw Error('Unsupported case file.');const out:Record<string,CaseState>={};for(const c of cases){const s=x.cases[c.id];if(!s)continue;const validReview=(d:any)=>{if(!d||['notes','rationale','analyst','disposition'].some(k=>typeof d[k]!=='string'||d[k].length>20000)||!['','More information needed','Refer to sanctions specialist','Propose false-positive closure'].includes(d.disposition)||!Array.isArray(d.pins)||d.pins.some((id:any)=>!c.documents.some(e=>e.id===id))||!d.comparisons||!d.requests)throw Error('Invalid case assessment.');for(const [k,v]of Object.entries(d.comparisons))if(!c.fields.some(([field])=>field===k)||!['Supports match','Challenges match','Unknown / unverified'].includes(v as string))throw Error('Invalid comparison.');for(const [k,v]of Object.entries(d.requests))if(!c.questions.some(([id])=>id===k)||typeof v!=='boolean')throw Error('Invalid evidence request.');return structuredClone(d) as Review};if(!Array.isArray(s.history)||s.history.length>20)throw Error('Invalid review history.');out[c.id]={draft:validReview(s.draft),history:s.history.map((h:any)=>{if(!h||!Number.isFinite(Date.parse(h.at))||!['Pending QC','Returned for correction','QC complete'].includes(h.outcome)||typeof h.finding!=='string'||h.finding.length>20000||typeof h.reviewer!=='string'||h.reviewer.length>20000||h.outcome!=='Pending QC'&&(!h.finding.trim()||!h.reviewer.trim()))throw Error('Invalid QC record.');return {...h,review:validReview(h.review)}})};}return out}
